language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
matrix:
  exclude:
    - os: osx
      compiler: gcc
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libosmesa6-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libqt4-dev qt4-qmake; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: travis_wait ./Scripts/oneshot-debug.sh
notifications:
  slack:
    secure: D03l+Pzfk8TAQfvqVw0Cw1v4IBNxvG8u/RxZ4BJ349x4Ty8AzbJz0EfoXPYVjyPTn8tXaPLKFPmlZxORBj4wb6z9iqTWTi0LKZ+cKfIRIKFGJj10U4UcKss8LZupcBTbaLX1u8UrwrThlLuoJcU/pmpc/h0VldJxCvOIyGabCgs=
